### ISSUE TITLE
Crash with Exploding Mobs

### ISSUE THREAD

**Issue by zzzqh** [Ladysnake/Lumen#6]
Exploding Mobs:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2884536-exploding-mobs-mod-a-death-effect-for-vanilla-mobs
Crash report:
https://paste.ubuntu.com/p/nXypBr9GCW/

**Comment by Pyrofab** [comment]
That one is definitely on their side, tell them to stop doing unchecked casts.

**Comment by zzzqh** [comment]
Got it, thanks
